// <auto-generated />
using System;
using MVC_ThomasMore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_ThomasMore.Migrations
{
    [DbContext(typeof(WebApiDataContext))]
    [Migration("20240926082724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_ThomasMore.Model.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestellingen", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KlantId = 1
                        });
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalPlaatsen")
                        .HasColumnType("int");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBadge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKleding")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWerkschoenen")
                        .HasColumnType("bit");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankrekeningNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Klanten", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankrekeningNummer = "123",
                            Gemeente = "Antwerpen",
                            Huisnummer = 12,
                            Naam = "Wouters",
                            PostCode = "3390",
                            Straat = "Steenweg",
                            Voornaam = "Michiel"
                        });
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Orderlijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductID");

                    b.ToTable("Orderlijnen", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aantal = 1,
                            BestellingId = 1,
                            ProductID = 1
                        },
                        new
                        {
                            Id = 2,
                            Aantal = 200,
                            BestellingId = 1,
                            ProductID = 2
                        });
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumToegevoegd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Producten", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumToegevoegd = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Naam = "Baldur's gate",
                            Prijs = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            DatumToegevoegd = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Naam = "Hello Kitty, Island adventure",
                            Prijs = 69.99m
                        });
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Bestelling", b =>
                {
                    b.HasOne("MVC_ThomasMore.Model.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Orderlijn", b =>
                {
                    b.HasOne("MVC_ThomasMore.Model.Bestelling", "Bestelling")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_ThomasMore.Model.Product", "Product")
                        .WithMany("OrderLijnen")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Bestelling", b =>
                {
                    b.Navigation("Orderlijnen");
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("MVC_ThomasMore.Model.Product", b =>
                {
                    b.Navigation("OrderLijnen");
                });
#pragma warning restore 612, 618
        }
    }
}
